### ISSUE TITLE
Fix IP List Parsing

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab2#13]
refactor cidr to ip list parsing, i.e. netIPv4Len vs len and incrementing ipv6 address in cidr block

**Comment by zakird** [comment]
@ajholland I'm not actually quite sure what this issue is about, but I didn't want to lose track of it either. Can you elaborate?

**Comment by ajholland** [comment]
The code currently uses golang's built in len() to find the length of an IP address, for some reason I must've thought there was a len function for ip's in golang's net package that I needed to switch to. Either way, there's not. 

The second part was I'm not 100% certain if zgrab2 can currently parse ipv6 cidr blocks and never got the chance to swing back around and figure that out.
