### ISSUE TITLE
tls: failed to parse certificate on 62.30.95.137:443?

### ISSUE THREAD

**Issue by chushuai** [zmap/zgrab2#190]
ip":"62.30.95.137","port":443,"protocol":"https"

"error":"tls: failed to parse certificate from server: asn1: structure error: explicitly tagged member didn't match"

But the certificate is legal

https://62.30.95.137/login

**Comment by chushuai** [comment]
The following is the certificate information obtained by other means
--------------------------------
Version: v3
Serial Number: 24705635162299587254707465229
Signature Algorithm: SHA256-RSA

Issuer:
CommonName: NiagaraAX
Organization: Tridium
Country: US

Validity:
Not Before: 2017-05-24 08:58 UTC
Not After : 2018-05-24 08:58 UTC

Subject:
CommonName: NiagaraAX
Organization: Tridium
Country: US

Subject Public Key Info:
Public Key Algorithm: RSA
Public Key:
Exponent: 65537
Public Key Modulus: (1024 bits) :
A9:3E:AF:72:1B:82:6D:99:7A:7F:3A:D5:DB:14:00:75:
69:21:6D:FA:BD:4F:7C:64:3F:95:73:7F:D7:3C:52:71:
BD:7B:0E:83:1F:D1:92:8C:1F:C8:53:54:4C:C7:66:8C:
82:47:A5:4F:55:86:CB:54:84:9B:DA:B0:CA:DC:09:F2:
66:6D:B2:F8:40:AC:F3:83:E8:76:CE:26:A6:A3:33:32:
6F:BA:0D:EE:B1:D3:E8:0B:FD:F4:66:67:FC:07:D3:63:
FD:E0:47:BB:92:6D:8B:6B:F2:87:74:C2:92:11:62:3C:
FF:2E:17:90:32:A5:58:BA:44:3A:C1:F0:5C:BB:7C:0D

Subject Key Identifier:
F0:03:DB:A7:9B:2D:84:70:E7:5B:93:BE:97:DC:44:E5:88:B6:09:04

Key Usage:
Digital Signature
Key Encipherment

Extended Key Usage:
Server Auth
Client Auth

Certificate Signature Algorithm: SHA256-RSA
Certificate Signature:
6D:45:90:D0:F0:CB:A5:A9:7F:2D:12:B1:28:2F:84:ED:
6A:3F:AA:A7:6E:5F:16:C2:AA:60:41:64:F0:7D:AB:2C:
C8:ED:E2:FF:FC:08:0C:34:08:A0:BD:29:8D:4E:73:9B:
C1:F1:56:1A:68:71:3C:04:6D:4C:1C:BF:BE:C2:97:F8:
7B:2D:FD:0B:FF:22:46:18:81:DB:17:86:E7:81:95:63:
57:98:46:E3:D9:B5:46:EA:B6:E4:9B:C7:CC:15:DA:10:
E1:45:ED:D4:EF:99:A7:EF:F5:00:A4:77:EA:4F:BD:59:
79:9C:CA:65:AF:68:81:DA:6A:5B:CA:22:52:C8:39:FC

**Comment by zakird** [comment]
The certificate has malformed ASN.1, which the Go ASN.1 parser is rejecting. Unfortunately, browsers tend to be a bit more lenient, but this doesn't look like a ZGrab bug.
