### ISSUE TITLE
Install fails in macOS 10.14 due to missing dependency

### ISSUE THREAD

**Issue by elitalon** [zmap/zgrab2#193]
Hello,

I'm trying to build zgrab2 but it fails with the following error:

```
cd cmd/zgrab2 && go build && cd ../..
../../modules/mongodb/scanner.go:9:2: cannot find package "gopkg.in/mgo.v2/bson" in any of:
	/usr/local/opt/go/libexec/src/gopkg.in/mgo.v2/bson (from $GOROOT)
	/Users/<redacted>/golang/src/gopkg.in/mgo.v2/bson (from $GOPATH)
```
Installing zgrab works without issues, so I guess this is a specific problem with zgrab2.

This is my current environment:
* OS: macOS 10.14
* Go installed with `brew install go`
* Environment variables:
  * `export GOPATH="${HOME}/<redacted>/golang"`
  * `export GOROOT="$(brew --prefix golang)/libexec"`
  * `export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"`

Let me know if you need any more info.

Thanks!

**Comment by zakird** [comment]
You'll need to install the various ZGrab dependencies. If you run 
```go get ./...
go build```. This should take care of it.

**Comment by duraki** [comment]
@zakird Why is this not in the README?
