### ISSUE TITLE
install fail in ubuntu

### ISSUE THREAD

**Issue by ericsuarez** [zmap/zgrab2#198]
When I try to install the package with the command  `go get github.com/zmap/zgrab2` (ubuntu) I get the following error. 

> github.com/zmap/zcrypto/x509
> go/src/github.com/zmap/zcrypto/x509/x509.go:84: undefined: asn1.NullRawValue

When I try to find the route https://github.com/zmap/zcrypto/x509 I get a 404 error. Should I've to install some package before? . Thank you

**Comment by zakird** [comment]
You likely have too old of a version of Go. Please use 1.10 or newer.

**Comment by gitxmax** [comment]
go version go1.12.2 linux/amd64

cd cmd/zgrab2 && go build && cd ../..
../../lib/ssh/kex.go:22:2: cannot find package "golang.org/x/crypto/curve25519" in any of:
        /usr/local/go/src/golang.org/x/crypto/curve25519 (from $GOROOT)
        /root/go/src/golang.org/x/crypto/curve25519 (from $GOPATH)
../../lib/ssh/keys.go:28:2: cannot find package "golang.org/x/crypto/ed25519" in any of:
        /usr/local/go/src/golang.org/x/crypto/ed25519 (from $GOROOT)
        /root/go/src/golang.org/x/crypto/ed25519 (from $GOPATH)
../../lib/smb/ntlmssp/crypto.go:9:2: cannot find package "golang.org/x/crypto/md4" in any of:
        /usr/local/go/src/golang.org/x/crypto/md4 (from $GOROOT)
        /root/go/src/golang.org/x/crypto/md4 (from $GOPATH)
../../lib/http/h2_bundle.go:48:2: cannot find package "golang.org/x/net/http/httpguts" in any of:
        /usr/local/go/src/golang.org/x/net/http/httpguts (from $GOROOT)
        /root/go/src/golang.org/x/net/http/httpguts (from $GOPATH)
../../lib/http/h2_bundle.go:46:2: cannot find package "golang.org/x/net/http2/hpack" in any of:
        /usr/local/go/src/golang.org/x/net/http2/hpack (from $GOROOT)
        /root/go/src/golang.org/x/net/http2/hpack (from $GOPATH)
../../lib/http/h2_bundle.go:47:2: cannot find package "golang.org/x/net/idna" in any of:
        /usr/local/go/src/golang.org/x/net/idna (from $GOROOT)
        /root/go/src/golang.org/x/net/idna (from $GOPATH)
../../lib/http/request.go:30:2: cannot find package "golang.org/x/text/unicode/norm" in any of:
        /usr/local/go/src/golang.org/x/text/unicode/norm (from $GOROOT)
        /root/go/src/golang.org/x/text/unicode/norm (from $GOPATH)
../../lib/http/request.go:31:2: cannot find package "golang.org/x/text/width" in any of:
        /usr/local/go/src/golang.org/x/text/width (from $GOROOT)
        /root/go/src/golang.org/x/text/width (from $GOPATH)
../../modules/mongodb/scanner.go:9:2: cannot find package "gopkg.in/mgo.v2/bson" in any of:
        /usr/local/go/src/gopkg.in/mgo.v2/bson (from $GOROOT)
        /root/go/src/gopkg.in/mgo.v2/bson (from $GOPATH)
Makefile:24: recipe for target 'zgrab2' failed
make: *** [zgrab2] Error 1
