### ISSUE TITLE
tls and banner

### ISSUE THREAD

**Issue by lambdafu** [zmap/zgrab2#213]
Hi,

can I use tls with banner together?  For example, "banner --tls" or "tls --probe DATA" would be great.  I can't find an option for that.

**Comment by rudrasingh99** [comment]
+1

**Comment by R-Romanov** [comment]
+1

**Comment by AnthraX1** [comment]
Hi,

I can do it. You mean grab banner after TLS connection is made?

**Comment by AnthraX1** [comment]
Pending https://github.com/zmap/zgrab2/pull/268

**Comment by lambdafu** [comment]
Yes, banner after tls to support some simple text-based services in case no better module exists. Thanks!

**Comment by AnthraX1** [comment]
> Yes, banner after tls to support some simple text-based services in case no better module exists. Thanks!

Pending review, but I've tested the fork locally and it works perfectly.

**Comment by zakird** [comment]
PR merged, closing.
