### ISSUE TITLE
Rate limiting requests

### ISSUE THREAD

**Issue by aPatinthehat** [zmap/zgrab2#221]
When using zgrab with the input file switch (-f) as a stand alone tool (without zmap), an error for 'socket: too many open files occurs'. I believe adding a rate limit should resolve this issue.

**Comment by R-Romanov** [comment]
@pat-inthe-hat It must be solved on enviroment side, not in the application. You should increase ulimits, this will solve the problem.

**Comment by zakird** [comment]
This can be solved by either increasing nmber of sockets or limiting number of light-weight routines.

**Comment by izhekov** [comment]
ulimit is unlimited still most of the requests results in errors like below. Seems the DNS server is in trouble.

{"domain":"asnpart.net","data":{"http":{"status":"connection-timeout","protocol":"http","result":{},"timestamp":"2022-01-29T22:44:12+01:00","error":"dial tcp: lookup asnpart.net on 185.12.64.1:53: dial udp 185.12.64.1:53: socket: too many open files"}}}

**Comment by zakird** [comment]
This error is not related to the server. Something on your local system is not enabling you to open the socket. It may be a system-enforced limit.

**Comment by mzpqnxow** [comment]
Another potential workaround is to use the comma-separated triplet format for the targets (fqdn, ip, trigger/tag)

This provides a few benefits:

1. No need for DNS resolution at runtime, except in the case of name-based redirects. The IP address(es) for each DNS name are already available when zgrab2 runs
2. Comprehensive coverage for DNS names that have multiple A record values

The caveat is that you'll be required to perform the DNS resolution and construct the targets file before invoking zgrab2. This is a step you must explicitly perform

For doing very large scale and comprehensive surveys, this is the best approach in my opinion. It's more effort than simply specifying a list of DNS names as targets to zgrab2, but you only need to write a script once to do this

You can follow this procedure:

- Prepare the list of FQDNs in a flat file
- Use a tool like [massdns](https://github.com/blechschmidt/massdns) to perform asynchronous A lookups all at once (at your specified rate, to your choice of resolvers)
- Use a simple jq script like the one I contributed to massdns [here](https://github.com/blechschmidt/massdns) to pull out the FQDN and IP pairs from the results file
- Use a simple script or one-liner to put the output into a zgrab2 compatible target file (fqdn, ip, trigger)

It's a lot more steps than what you have in mind, but as I said, it's a very small amount of code that only needs to be written once. Plus, you get the benefit of capturing data from both (www.bah.com, 1.2.3.4) *and* (www.bah.com, 1.2.3.5) which will give you a chance to find inconsistencies in the behavior of servers for the same site

If you're interested in using this approach I'm happy to put a gist up with the few things I use to automate it. I've found it to work very well
