### ISSUE TITLE
How to use zgrab2 as a package

### ISSUE THREAD

**Issue by R-Romanov** [zmap/zgrab2#222]
I want to import zgab2 into my project and use the "Grab" structure. 

If i just add zgrab to the import section, i will get an error:
`vendor/github.com/zmap/zgrab2/utility.go:52:39: parser.ParseCommandLine undefined (type *flags.Parser has no field or method ParseCommandLine)`

Please give me advice on how to properly use your wonderful tool as a package.

**Comment by edermi** [comment]
You have to use https://github.com/zmap/zflags as flags provider by explicitly importing it.

**Comment by R-Romanov** [comment]
@edermi 
I will be very grateful for the simple code sample.

**Comment by edermi** [comment]
I ran into the same problem with [nray](https://github.com/nray-scanner/nray) - Adding `github.com/zmap/zflags` to `go.mod` solved the issue.

If you are not using Go modules yet, removing the existing parser Go fetched from your `GOPATH` and `go get`ting the library to have it available in `GOPATH` should also work.

**Comment by R-Romanov** [comment]
@edermi 
Thank! This completely solved my problem.
