### ISSUE TITLE
Configuration file input-file / output-file not functioning as documented

### ISSUE THREAD

**Issue by mzpqnxow** [zmap/zgrab2#236]
I will take a look through the source, but the example in the README does not work for the multiple mode with a configuration file. Using it exactly as documented:

```
 $ echo www.google.com > input.txt
 $ cat multiple.ini               
[Application Options]
output-file="output.txt"
input-file="input.txt"
[http]
name="http80"
port=80
endpoint="/"
[http]
name="http8080"
port=8080
endpoint="/"
[ssh]
port=22
 $ zgrab2 multiple -c multiple.ini
INFO[0000] started grab at 2020-01-08T21:12:57Z         
...
<hangs reading from stdin>
```

It seems it is not acting on the `input-file` parameter as it is stuck reading from stdin, which is the default behavior when no `input-file` is specified on the command-line or configuration file

I verified it is indeed blocking on a read of stdin using strace. After starting up, it reads the configuration file but never attempts to stat or open `input.txt`, then it just blocks on stdin until you kill it or send EOF/Control-D

It's an easy workaround to just pipe the input to stdin, but this is a really silly bug (in either code or documentation)

Am I missing something here?

EDIT: The output-file parameter doesn't work either, if I pipe hosts to stdin, it spits the results out to stdout

**Comment by mzpqnxow** [comment]
A very, very quick check for the possible cause ...

```
~/zgrab2 $ git pull
~/zgrab2 $ find . -name \*.go -exec grep -Hni 'application options' {} \;
~/zgrab2 $
```

Maybe the `Application Options` literal is stored in some non-standard way, but this makes me wonder if this block of logic is possibly missing from the code..

**Comment by mzpqnxow** [comment]
I _think_ all that needs to be done is here is parse the `[Application Options]` section so that the input and outfile settings can be plugged in. Parsing the other sections seems to work as expected. For example, in the above example, when I use:

`echo www.google.com | zgrab2 multiple -c multiple.ini` it does in fact execute both sections ("http80" and "http8080") ... it's just that global / `Application Options` section that seems to be completely ignored. I can only assume it was never used and therefore never implemented?

**Comment by simplegithubusername** [comment]
work well with `./zgrab2 -f tcp80.csv -o zgrabresults.json multiple -c multiple.ini`

**Comment by mzpqnxow** [comment]
@simplegithubusername yes, that's how I am using it now. The issue is that these parameters will not be accepted from an ini file, hence the title of the issue- "Configuration file input-file / output-file ..."

It's much less clunky to be able to specify this via a single ini / configuration file if you have (for example) thousands of batches of ini files with separate target files, and separate output files. Rather than generating a long list of commands that include unique `-f` and `-o` settings in advance or dynamically with a for loop, you can just iterate over `ini` files without specifying anything else

It's really just a matter of convenience and cleanliness- but I guess it's not a big deal. I thought I might come back with a PR but it's already been 6 months.. so probably not :)

I'll close this out
