### ISSUE TITLE
FEATURE REQUEST: Add global option --exclude or --exclude-file to exclude addresses/hostnames

### ISSUE THREAD

**Issue by mzpqnxow** [zmap/zgrab2#254]
Many mass network probe tools support `--exclude` or similar, where the user can provide a list of hostnames or IP addresses and the tool will skip over any probe that would have went to that host.

This is a very useful and relatively simple feature. It can of course be done by pre-processing the list you provide to zgrab2, but that can be clunky, especially when using zgrab2 at a very large scale (think LANs with > 250000 nodes, or edges with 50000 FQDNs)

Is this something that would be considered as a reasonable feature?

**Comment by tsellers-r7** [comment]
A benefit to the functionality would be the ability to exclude addresses when using hostnames.

**Comment by mzpqnxow** [comment]
This isn't a priority for me, no time 😞
