### ISSUE TITLE
Add --ftps to ftp module

### ISSUE THREAD

**Issue by lambdafu** [zmap/zgrab2#255]
Hi,
thanks for zgrab2! I noticed that the imap module has an option --imaps and an option --starttls, for implicit and explicit TLS respectively. But the ftp module has only --authtls, which corresponds to starttls in IMAP, while the implicit TLS negotiation is currently not possible.  It would be nice to have an option --ftps that directly negotiates TLS, as is common on port 990. Thanks!

**Comment by lambdafu** [comment]
#264

**Comment by codyprime** [comment]
This is on master now as of 475c10307.  The flag is `--implicit-tls`
