### ISSUE TITLE
[PR Open] Improving retry-https by reading HTTP 400 and/or adding `--retry-http`

### ISSUE THREAD

**Issue by mzpqnxow** [zmap/zgrab2#273]
The `retry-https` feature of the `zgrab2` `http` module is very useful when surveying a large collection of non-standard port. Based on measurements that I do regularly, it seems HTTPS (as opposed to HTTP) on non-standard ports is becoming more and more common, where it used to be almost entirely HTTP

However, the current implementation of `retry-https` only retries as HTTPS when the plaintext request does not result in an RFC compliant HTTP response. By design, it does not look at the response code or message to make any decisions. This was a reasonable choice to me but I am now encountering quite a bit of cases where additional/different logic could make `zgrab2` more effective in dealing with this

A specific case of the problem this approach runs into is the below. This is from nginx in a pretty basic/default HTTPS configuration. I'm not sure about how common it is with Apache or other servers. I'm happy to provide some numbers from a large sample set to give an idea of the magnitude of the problem, or on what other server software exhibits this behavior

The following shows a plaintext HTTP request made to an HTTPS endpoint. NGINX returns an RFC compliant HTTP response back- specifically, an HTTP 400 with a clear description of what happened- HTTP request made to SSL endpoint

```
> GET / HTTP/1.1
> Host: somesite.com:8443
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Server: nginx
< Date: Tue, 25 Aug 2020 13:46:39 GMT
< Content-Type: text/html
< Content-Length: 248
< Connection: close
< 
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>
```

Per [RFC7231, 6.5.1](https://tools.ietf.org/html/rfc7231#section-6.5.1):

> The 400 (Bad Request) status code indicates that the server cannot or
> will not process the request due to something that is perceived to be
> a client error (e.g., malformed request syntax, invalid request
> message framing, or deceptive request routing).

So clearly HTTP 400 does not necessarily mean an HTTP request was sent to an HTTPS listener, but it may be the most common meaning on the modern Internet for HTTP 400 statistically. I'm not sure but could gather some statistics

I would much prefer if servers that are configured to serve *only* HTTPS would simply kill the SSL/TLS negotiation as invalid rather than `MSG_PEEK` at the socket contents and try to cleverly detect a plaintext request, but it seems this is not how the developers of NGINX chose to do things.

If this is considered something in scope for `zgrab2` to handle, I came up with three possible approaches to making this more robust/effective for this sort of case:

1. Keeping `retry-https` as a feature, but incorporate checking the layer-7 protocol response code (and possibly the content of the error message) and retrying as HTTPS if some hard-coded conditions specific to a well-formed HTTP response are met that suggest it should be an HTTPS request
2. Providing an option `retry-https-code` to the user, who can specify `400`, or whatever they prefer. This makes it flexible and also has no impact on how the module currently operates for existing users
3. Implementing an option `retry-http` to do the inverse of `retry-https`. By default make HTTPS requests, falling back to HTTP on a SSL/TLS handshake failure. I think it would want to only fall back to HTTP if the SSL/TLS HELO received no valid protocol response at all, to avoid retrying as HTTP when there are, e.g. cipher negotiation errors or failures due to client-cert requirement failures

Absent any desire to implement this natively in `zgrab2`, it's always possible for the user to post-process the `zgrab2` output from `retry-https` and identify these cases themselves using a script that produces another set of commands/ini/target files which are then used for a second run on these hosts, set to use HTTPS explicitly

Any thoughts on this?

If I had to choice, for the purpose of simplicity and effectiveness, I would like `retry-https-code = 400`, even though it probably won't be perfect. The other options seem to be more work and complexity

EDIT: Reference the PR I sent for this to see what I chose, I think it's the most intuitive, simple and non-invasive way to do this

**Comment by mzpqnxow** [comment]
There may be some cases where it's desired to capture the 400 as well as perform the retry and capture that. But the complexity of  doing that seems far beyond the value, unless I'm missing a simple way of doing it- I guess it would be some hack to make it similar to a 301/302. The best I can think of for a simple way to indicate that this behavior was encountered would be to add a a field in the output- but I'm not sure that's worth the effort or the disruption to the schema of the output file

**Comment by mzpqnxow** [comment]
Thank you @zakird for merging this! I'm closing the issue now

**Comment by matansbs** [comment]
How about consider status as failed if json returned contains a strings that way one can determine what can consider as a retry solution

**Comment by matansbs** [comment]
@mzpqnxow

**Comment by mzpqnxow** [comment]
If what you're describing is a standard message for some ubiquitous software, possibly worth considering

But if it's application-specific, or configuration-specific, or not common, I don't think it would make a lot of sense to add. Remember these checks are _cheap_ but they're not _free_- expanding them adds up in CPU cycles

Of it was to be implemented, it might make the most sense as a runtime option, so a user could specify their own patterns or strings, but that's not something I have time to implement at the moment, and I don't have any personal use-cases to motivate me to make the time

Sorry!
