### ISSUE TITLE
How to add ports to scan

### ISSUE THREAD

**Issue by DimaTarVN** [zmap/zgrab2#280]
I have a scanning with 1000 ports, and I wanna send request like **ip+port**, how can I do it, without making 1000 config files?

**Comment by kaspers1778** [comment]
Also looking for that

**Comment by mzpqnxow** [comment]
This isn't too different than making 1000 config files- but you can do this with a single target file and a single config file by joining them into one. Example:

targets.csv:
```
1.2.3.4, somesite.com,http_443
1.2.3.4, somesite.com,http_80
```

config.ini:
```
[http]
name = http_443
trigger = "http_443"
endpoint = "/"
port = 443
max-redirects = 3
use-https = True

[http]
name = http_80
trigger = http_80
endpoint = "/"
port = 80
max-redirects = 3
retry-https = True
```

Invoke as:

```
cat targets.csv | zgrab2 multiple -c config.ini
```

This is only 2 ports obviously- to do more, it's trivial to write a simple loop in bash (or whatever you choose) to generate a single ini file with all of the triggers in them:

```
$ echo > privileged_ports.ini
$ cat > base_config.ini << 'EOF'
 [http]
name = http:port:%PORT%
trigger = "http:port:%PORT%"
endpoint = "/"
port = %PORT
max-redirects = 3
EOF
$ for port in $(seq 1 1024); do
  sed -e "s/%PORT%/$port/" base_config.ini >> privileged_ports.ini
done
```

This allows you to use a single invocation:

```
$ cat targets.csv | zgrab2 multiple -c privileged_ports.ini
```

I'm fairly certain this is the only/best way to do this. Hope it's helpful

**Comment by dadrian** [comment]
Correct, we don't support this right now. You could try importing ZGrab2 as a library and writing a custom Go program.
