### ISSUE TITLE
http tests fail

### ISSUE THREAD

**Issue by Mindavi** [zmap/zgrab2#291]
The http tests fail for me:

```
$ go version
go version go1.15.5 linux/amd64

$ go test github.com/zmap/zgrab2/lib/http
--- FAIL: TestReadRequest (0.00s)
    readrequest_test.go:438: #3: error "parse \"../../../../etc/passwd\": invalid URI for request", want error "parse ../../../../etc/passwd: invalid URI for request"
    readrequest_test.go:438: #4: error "parse \"\": empty url", want error "parse : empty url"
--- FAIL: TestClientRedirects (0.01s)
    client_test.go:236: with default client Get, expected error "Get /?n=10: stopped after 10 redirects", got "Get \"/?n=10\": stopped after 10 redirects"
    client_test.go:242: with default client Head, expected error "Head /?n=10: stopped after 10 redirects", got "Head \"/?n=10\": stopped after 10 redirects"
    client_test.go:249: with default client Do, expected error "Get /?n=10: stopped after 10 redirects", got "Get \"/?n=10\": stopped after 10 redirects"
    client_test.go:256: with default client Do and empty Method, expected error "Get /?n=10: stopped after 10 redirects", got "Get \"/?n=10\": stopped after 10 redirects"
--- FAIL: TestFileServerZeroByte (0.00s)
    fs_test.go:589: parse "http://127.0.0.1:38853/..\x00": net/url: invalid control character in URL
--- FAIL: TestTransportCancelRequestInDial (0.00s)
    transport_test.go:1690: Got events:
        dial: blocking
        canceling
        Get = Get "http://something.no-network.tld/": net/http: request canceled while waiting for connection
        
        Want:
        dial: blocking
        canceling
        Get = Get http://something.no-network.tld/: net/http: request canceled while waiting for connection
--- FAIL: TestTransportRejectsAlphaPort (0.00s)
    transport_test.go:3534: got error "invalid port \":123foo\" after host"; want "invalid URL port \"123foo\""
FAIL
FAIL    github.com/zmap/zgrab2/lib/http 29.559s
FAIL
```

Also happens on go 1.14 for me.

Other tests also fail for me, but let's start at this. Is it that this is OS-dependent or are there some incorrect assumptions about the go error messages built into the tests?

**Comment by engn33r** [comment]
I think [the Makefile has comments](https://github.com/zmap/zgrab2/blob/17a5257565c758e2b817511d15476d330be0a17a/Makefile#L15) that address this stating `some of the third-party libraries in lib (e.g. http) are failing.` Tracing things back to commit aaa9da4 that introduced this comment indicates `make clean zgrab2 test` is probably the way to run tests. I would guess this is a known issue and therefore tests are run differently that what you attempted.

**Comment by Mindavi** [comment]
Seems logical. I was looking at packaging zgrab for nixpkgs, because a friend of mine likes the tool. I am not interested anymore in packaging and apparently these test issues are known. In general, my feeling is that this project doesn't get much attention from the maintainer(s) anyway. At least not with regards to general quality.

For anyone reading this: consider just removing the tests if they don't work, or fix them (some tests are easy to fix).
