### ISSUE TITLE
Recover original image from zgrab output

### ISSUE THREAD

**Issue by BuileaTM** [zmap/zgrab2#341]
To test the zgrab tool I scannend one IP for the presence of picture123.jpg
This is the original header of the image
![image](https://user-images.githubusercontent.com/58303884/149528124-e454fd11-c08a-4383-8429-d6e573c15eba.png)

So I ran zgrab against this IP:
`./zgrab2 http -s 10  -o output.txt --method GET --endpoint "/wp-content/uploads/picture123.jpg" -f input.txt`

But when I compared the original image with the downloaded image (in the `output.txt` file) I noticed some diffrences:
```
root@hostname:/zmap/zgrab2@v0.1.7# jq -r '.data.http.result.response.body' output.txt | xxd | more
00000000: c3bf c398 c3bf c3a0 0010 4a46 4946 0001  ..........JFIF..
00000010: 0101 0060 0060 0000 c3bf c39b 0043 0005  ...`.`.......C..
00000020: 0304 0404 0305 0404 0405 0505 0607 0c08  ................
00000030: 0707 0707 0f0b 0b09 0c11 0f12 1211 0f11  ................
00000040: 1113 161c 1713 141a 1511 1118 2118 1a1d  ............!...

```

I also wiretapped the HTTP request / response with Wireshark and I saw in the network traffic that the original image was downloaded correctly. So it seems have somthing to do with the 'data at rest'.  Am I missing some sort of encoding? Could anyone please help me with recovering the original image from the json  `output.txt` file?

**Comment by p-l-** [comment]
Hi,

The body is encoded, see #263 (I think this issue might be a duplicate).

**Comment by BuileaTM** [comment]
Does anyone has a sort of workarround for this? Because also the filehash don't match with the original file.

**Comment by dadrian** [comment]
This is an encoding issue. I believe there is a flag to base64 HTTP outputs
