### ISSUE TITLE
Name Constraints schema is incorrect

### ISSUE THREAD

**Issue by dadrian** [zmap/zgrab2#35]
See #34 but for name constraints.

> JSON object specified for non-record field: `data.tls.server_certificates.chain.parsed.extensions.name_constraints.excluded_ip_addresses`

**Comment by dadrian** [comment]
I think it's actually just `excluded_ip_addresses` and `permitted_ip_addresses` IP addresses that are incorrect. They should be objects.

**Comment by justinbastress** [comment]
Seems there were also the `edi_party_names` and `registered_ids` missing.

I did fix some blatant issues when I first copied it over, but my `openssl req -new -x509` SSL certificates obviously don't exercise the whole schema.

**Comment by dadrian** [comment]
In an ideal world this is something that is tested and maintained as part of the ZCrypto project, and we generate certs with every field in the test code there.

**Comment by dadrian** [comment]
Fixed in #36
