### ISSUE TITLE
Possible?

### ISSUE THREAD

**Issue by Octolus** [zmap/zgrab2#353]
Hi,

Looking for a specific command for this task.

- Several IP Ranges
- Will scan for one specific domain that will be sent as "Host: domain.tld" header
- Will look for a specific keyword, then print the specific IP found that matches I.

long story short, basically looking to find the backend of a server that has reverse proxy by scanning the internet.

**Comment by JohnEskimSmith** [comment]
Hi, 
You have 2 options to solve the you problem
1. Best solution: you can create your payload(probe) with the banner module. In the payload, you simply indicate your commands in accordance with http, like same, for instance, - b'GET / HTTP/1.0\r\nUser-Agent: curl/7.68.0\r\nAccept: */*\r\n\r\n'
2. The second option, developers zgrab2 forgive me , you can see how it is implemented in my code

https://github.com/JohnEskimSmith/PacketSenderLite 
(https://github.com/JohnEskimSmith/PacketSenderLite/blob/master/example_python_payloads/http_get.py)
https://github.com/JohnEskimSmith/PacketSenderHTTPLite

**Comment by mzpqnxow** [comment]
> Hi,
> 
> 
> 
> Looking for a specific command for this task.
> 
> 
> 
> - Several IP Ranges
> 
> - Will scan for one specific domain that will be sent as "Host: domain.tld" header
> 
> - Will look for a specific keyword, then print the specific IP found that matches I.
> 
> 
> 
> long story short, basically looking to find the backend of a server that has reverse proxy by scanning the internet.

This is relatively straightforward if you use the CSV formatted targets input. Lines look like this (I may mixup the first 2 columns)


    1.2.3.4, www.target.com
    2.3.4.5, www.target.com
    3.4.5.6, www.target.com
    ...

For that input, the HTTP Host header (and SNI and certificate logic) will be set to www.target.com
