### ISSUE TITLE
Support opt-out (or make zgrab opt-in)

### ISSUE THREAD

**Issue by Martmists-GH** [zmap/zgrab2#395]
Over the last few days, many of my servers have been getting spam-pinged by the zgrab user agent, resulting in much lower responses from my application. Please add a way for small developers to opt out.

**Comment by zakird** [comment]
We don't maintain any global blacklist within the project and do not plan to. This is going to be based on the individual operator.

**Comment by Martmists-GH** [comment]
Then what am I supposed to do to protect my servers?

**Comment by jamadden** [comment]
Reputable scanners will put contact information in their headers. Contact them and they will add you to their blocklist.

Unreputable scanners won't, but they wouldn't put you in a blocklist anyway.
