### ISSUE TITLE
Is this repo unmaintained?

### ISSUE THREAD

**Issue by AnthraX1** [zmap/zgrab2#409]
The owners have not approved nor responded to a single PR in the last 6 months...

**Comment by mzpqnxow** [comment]
It is maintained

I'm not sure where you got your data from but I see 4-5 PRs merged in the past 5 months

**Comment by AnthraX1** [comment]
https://github.com/zmap/zgrab2/commits/master/

Well, before you answered the last commit was Aug 7, 2023.

Seems owners are back now.
