### ISSUE TITLE
Remove ZGrab as a dependency

### ISSUE THREAD

**Issue by ajholland** [zmap/zgrab2#48]
s#zgrab/ztools#zgrab2/tools#g

https://github.com/zmap/zgrab2/search?utf8=%E2%9C%93&q=ztoolsKeys&type=

**Comment by ajholland** [comment]
Sounds great, thanks!

**Comment by jordan-wright** [comment]
100% up to y’all, but we might want to keep this one open until changes are made to zcrypto to also remove zgrab references.
