### ISSUE TITLE
utility.go comments

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab2#7]
Some notes of things to be fixed up.

https://github.com/zmap/zgrab2/blob/master/utility.go
`func ParseInput(s string) (*net.IPNet, string, error) {`

This could use a better name. What kind of input is being parsed? At first I thought this was handling command-line arguments. Also, please put spaces in comments. :D 

It seems strange that this function returns a pointer and a string. Why not just return the `net.IPNet`? I can't imagine this is a large object. 

```
case j == -1:
		//ip,domain
		str := strings.Split(s, ",")
```

This should also handle the case "ip, domain". That's inevitably going to happen.

**Comment by ajholland** [comment]
net.IPNet doesn't contain a domain name, and by this point I parse input into whether or not it has an IP that we can parse out of it, if we can't it returns a string to be used as domain name

**Comment by ajholland** [comment]
Resolved by [7f71198](https://github.com/zmap/zgrab2/commit/7f71198296109f0e08561c35931f8bb79494e235)
