### ISSUE TITLE
module tls or http check heartbleed doesn't work

### ISSUE THREAD

**Issue by etmatrix** [zmap/zgrab2#91]
I'm testing zgrab2 on server vulnerable to heartbleed, but module tls or http tell me the host is not vulnerable to heartbleed.

    zgrab2 http --heartbleed -p 443 --use-https

or

    zgrab2 tls --heartbleed -p 443

output:

    "heartbleed_log":{"heartbeat_enabled":false,"heartbleed_vulnerable":false}}

I tried with zgrab, the result output is correct.

**Comment by etmatrix** [comment]
@justinbastress yes confirm, with option `--heartbeat-enabled` zgrab2 report as vulnerable

**Comment by etmatrix** [comment]
I compared the client hello between zgrab and zgrab2, I see in zgrab2 is missing also this extension: signed_certificate_timestamp.
I'm not expert on SSL/TLS protocol, maybe is useful request also this extension to server.

**Comment by zakird** [comment]
I'm moving this to its own issue. It's unrelated to the original.
